### ISSUE TITLE
Add resource links to Open Data sources

### ISSUE THREAD

**Issue by andreipopovici** [jshacks/bucharest#2]
As discussed briefly [on Facebook](https://www.facebook.com/events/554913261366690/permalink/558853294306020/), it would be a good idea to provide participants with a handy list of open data they could use during the hackathon.

Some of the sources:
- [in an exhaustive spreadsheet](https://docs.google.com/spreadsheets/d/1Fz5Cj7cN1Trg4tYyQOajlgQxCKby4HXTZc5Rh8vyic0/edit#gid=0)
- [Data.gov.ro](http://data.gov.ro)
- [a list of all public agencies](http://www.zf.ro/zf-24/exclusivitate-zf-vedeti-aici-lista-celor-256-de-agentii-guvernamentale-la-sfarsitul-anului-2008-4699798)

Where would be the best place to put these?

**Comment by afruth** [comment]
I'll try to make a list in a new repository.

**Comment by afruth** [comment]
I made a list here: https://github.com/jshacks/OpenData

Fell free to make PR's :)
